services:
  postgres:
    image: postgres:15-alpine
    hostname: copilot-postgres
    container_name: copilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Recife
      PGTZ: America/Recife
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d copilot"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
